version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      product: hello
      subProduct: hello2
      environment: Production
      token: $ARMORCODE_TOKEN
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
      end: 30
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              token=5399947e-cfbc-4d9b-95a5-dd4e8d7a32d2
              wget https://app.armorcode.com/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate
