version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      product: test_pro
      subProduct: testCC
      environment: Production
      token: $ARMORCODE_TOKEN
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
      end: 30
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              token=80d9a917-1c80-429a-8975-07b11c6ca75a
              wget https://qa.armorcode.ai/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate
